### ISSUE TITLE
Uninstallation of the plugin?

### ISSUE THREAD

**Issue by github-luckow-org** [Leuchtfeuer/mautic-deutschepost#1]
If I remove the triggerdialog plugin from inside the directory and after I deleted the /cache/* I got the following errors in the logfile:

`Symfony\\Component\\Debug\\Exception\\ClassNotFoundException: Attempted to load class "ConfigSubscriber" from namespace "MauticPlugin\\MauticTriggerdialogBundle\\EventListener".\nDid you forget a "use" statement for e.g. "Mautic\\QueueBundle\\EventListener\\ConfigSubscriber", "Mautic\\EmailBundle\\EventListener\\ConfigSubscriber", "Mautic\\CoreBundle\\EventListener\\ConfigSubscriber", "Mautic\\AssetBundle\\EventListener\\ConfigSubscriber", "Mautic\\SmsBundle\\EventListener\\ConfigSubscriber", "Mautic\\CampaignBundle\\EventListener\\ConfigSubscriber", "Mautic\\ApiBundle\\EventListener\\ConfigSubscriber", "Mautic\\ConfigBundle\\EventListener\\ConfigSubscriber", "Mautic\\ReportBundle\\EventListener\\ConfigSubscriber", "Mautic\\UserBundle\\EventListener\\ConfigSubscriber", "Mautic\\PageBundle\\EventListener\\ConfigSubscriber", "Mautic\\LeadBundle\\EventListener\\ConfigSubscriber", "Mautic\\WebhookBundle\\EventListener\\ConfigSubscriber", "MauticPlugin\\MauticSocialBundle\\EventListener\\ConfigSubscriber" or "MauticPlugin\\MauticLdapAuthBundle\\EventListener\\ConfigSubscriber"? - in file /app/code/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php - at line 138`

The whole site is offline till i put the plugin back into to plugin folder. Do you have an advice for me how to uninstall the plugin?

**Comment by ekkeguembel** [comment]
Researching.

**Comment by FlorianWessels** [comment]
Hi,

could you provide more information on your environment (Mautic version, debug or production mode, etc.). It seems to me, that this is a general problem and was not cause by the plugin.

Thanks
Flo

**Comment by lellebebbl** [comment]
I was able the reproduce the error. I tested some other plugins which all worked when I deleted it.
The error will only appear if you use the `php app/console cache:clear` command. If you use `rm -rf app/cache/prod/*` it works.

**Comment by github-luckow-org** [comment]
solves it for me. thank you.
