### ISSUE TITLE
Secret fields are displayed in plain text

### ISSUE THREAD

**Issue by stefanvetter** [Leuchtfeuer/mautic-deutschepost#20]
**Describe the bug**
When I enter the "Prod JWT Secret" and the "Authentication Secret" and save them, they are shown in plain text. This allows any user of the instance with access to the settings to just copy them out and use them for unwanted purposes.

**To Reproduce**
1. Enter secrets
2. Save
3. Secrets are visible

**Expected behavior**
I would expect that a "password" style field would be used for the secrets so they are not shown in the interface and cannot be copied out.

**Screenshots**

<img width="825" alt="plugin-conf" src="https://user-images.githubusercontent.com/6615327/145365038-1c2ba2d4-ba72-4161-af1d-472ae7700053.png">

**Comment by oltmanns-leuchtfeuer** [comment]
This Issue was fixed in #23 and is shipped in the new release.

**Comment by stefanvetter** [comment]
Awesome, thank you!
