### ISSUE TITLE
Old Print Mailing Templates can't be deleted in Mautic

### ISSUE THREAD

**Issue by dsp76** [Leuchtfeuer/mautic-deutschepost#26]
**Describe the bug**
I try to delete my "test" Print Mailing Templates. However, they can't be deleted. Not as admin (all rights), also not as user with the delete right explicitly granted.

**To Reproduce**
1. create a template
2. try to delete it

**Expected behavior**
should be deleted

**Screenshots**
log: [2022-03-25 17:36:00] mautic.CRITICAL: Uncaught PHP Exception MauticPlugin\MauticTriggerdialogBundle\Exception\RequestException: "Zugriff auf die Ressource verweigert. Nicht genügend Berechtigungen." at MASKED/httpdocs/plugins/MauticTriggerdialogBundle/Service/TriggerdialogService.php line 169 {"exception":"[object] (MauticPlugin\\MauticTriggerdialogBundle\\Exception\\RequestException(code: 1605089193): Zugriff auf die Ressource verweigert. Nicht genügend Berechtigungen. at MASKED/httpdocs/plugins/MauticTriggerdialogBundle/Service/TriggerdialogService.php:169)"} []

**Mautic version**
4.2

**Comment by ekkeguembel** [comment]
confirmed, known issue - will tackle that!

**Comment by ekkeguembel** [comment]
BTW deleting from Database is supposed to be safe :)

**Comment by jos0405** [comment]
UPVOTE :) 
Ich habe das gleiche Problem.
