### ISSUE TITLE
WORKAROUND: Update to Mautic 4.2.1 requires re-authentication ("your configuration seems to be invalid")

### ISSUE THREAD

**Issue by ekkeguembel** [Leuchtfeuer/mautic-deutschepost#27]
For some unknown reason, update to 4.2.1 invalidates the plugin authentication: 
In the "Print Mailing" menu item, a yellow box message 
`Your configuration seems to be invalid. Please check your [Configuration]`
is displayed.

Solution: Go to Configuration -> Print Mailing Settings
and re-enter _Prod JWT Token_ as well as _Authentication Secret_

This will fix the issue.

(Root cause currently not investigated.)

**Comment by dsp76** [comment]
Thanks! This works for us.
