### ISSUE TITLE
Mautic v3 compatibility

### ISSUE THREAD

**Issue by dsp76** [Leuchtfeuer/mautic-deutschepost#3]
mautic-deutschepost plugin doesn't work with Mautic 3 (3.0.1)

It fails with:

`Class "Mautic\CoreBundle\EventListener\CommonSubscriber" not found while loading "MauticPlugin\MauticTriggerdialogBundle\EventListener\ConfigSubscriber".`

Reason:
_CommonSubscriber removed. Implement Symfony\Component\EventDispatcher\EventSubscriberInterface directly and use DI instead._

(from: https://github.com/mautic/mautic/blob/8cb3c509a09224fe9c71abe84faebdb69c11c934/UPGRADE-3.0.md)

**Comment by flossels** [comment]
The bundle is currently only compatible with Mautic 2.16.x, but we are working on a solution to make it compatible with M3. However, due to lack of time and other projects, we will probably not be able to tackle the adjustments until a few weeks.
