### ISSUE TITLE
Compatibility Mautic 5

### ISSUE THREAD

**Issue by saschafoerster** [Leuchtfeuer/mautic-deutschepost#45]
**Is your feature request related to a problem? Please describe.**
I tried to install the plugin with Mautic 5 upwards 

With Mautic 5.0.4 I got the following errors: 

Error in browser: 
`The "app/bundles/CoreBundle/Resources/views/Offline" directory does not exist ("//app/bundles/CoreBundle/Resources/views/Offline").`

Error in logs: 
`PHP Fatal error:  Declaration of MauticPlugin\LeuchtfeuerPrintmailingBundle\LeuchtfeuerPrintmailingBundle::onPluginUpdate(Mautic\PluginBundle\Entity\Plugin $plugin, Mautic\CoreBundle\Factory\MauticFactory $factory, $metadata = null, ?Doctrine\DBAL\Schema\Schema $installedSchema = null) must be compatible with Mautic\PluginBundle\Bundle\PluginBundleBase::onPluginUpdate(Mautic\PluginBundle\Entity\Plugin $plugin, Mautic\CoreBundle\Factory\MauticFactory $factory, $metadata = null, ?Doctrine\DBAL\Schema\Schema $installedSchema = null): void in /var/www/html/mautic/docroot/plugins/LeuchtfeuerPrintmailingBundle/LeuchtfeuerPrintmailingBundle.php on line 12
`

**Comment by ekkeguembel** [comment]
High Sascha, m5 is indeed not supported as of today. I will contact you on Slack :)
