### ISSUE TITLE
Plugin ignores complete path when installed in subdirectory

### ISSUE THREAD

**Issue by dsp76** [Leuchtfeuer/mautic-deutschepost#8]
**Describe the bug**
Triggerdialog config link won't respect the subdirectory where Mautic is installed.
E.g. https://MAUTICDOMAIN/s/config/edit#triggerdialogconfig instead of https://MAUTICDOMAIN/go/s/config/edit#triggerdialogconfig

**Mautic version**
3.1.2

**Additional context**
minor issue, just want to make sure there are no other references to mautic path which may break the plugin to work correctly

**Comment by dsp76** [comment]
Actually that could be the reason the configuration is said to be invalid?

![image](https://user-images.githubusercontent.com/1241376/99098757-bc2b0900-25d9-11eb-9127-de29450fa554.png)

**Comment by luguenth** [comment]
the wrong Configuration bug gets fixed in the referenced PR. But the path still is not dynamically.
